baseurl = "https://conrads.website/"
languageCode = "en-us"
title = "Conrad's Website"
theme = "Coder"
publishDir = "docs"

PygmentsCodeFences = true
# PygmentsUseClasses = true
PygmentsStyle = "monokai"


[params]
  author = "Conrad Mearns"
  info = "Bachelor of Computer Science"
  keywords = "conrad, mearns, blog"

  [blackfriday]
    extensions = ["hardLineBreak"]

[[params.social]]
  name = "Github"
  weight = 1
  url = "https://github.com/Conradmearns"

[[params.social]]
  name = "Twitter"
  weight = 3
  url = "https://twitter.com/conrad_mearns"

[[menu.main]]
  name = "Scraps"
  weight = 2
  url = "/posts/"

[[menu.main]]
  name = "Resume"
  weight = 1
  url = "/about/"

[[menu.main]]
  name = "List"
  weight = 5
  url = "/list/"

[markup.goldmark.renderer]
unsafe= true